### ISSUE TITLE
Fails on emscripten 3.1.65

### ISSUE THREAD

**Issue by SGSSGene** [qlibs/reflect#62]
Compiling the header with emscripten 3.1.65 fails (works fine with 3.1.61)

Reproduce:
```
# download and activate emscripten:
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest

# download refelect
cd ..
git clone https://github.com/qlibs/reflect.git
cd reflect

# compile
source ../emsdk/emsdk_env.sh
em++ -x c++ reflect -std=c++20
```

<details>
<summary><b>The error that it produces:</b></summary>

```sh
reflect:758:36: warning: unknown warning group '-Wenum-constexpr-conversion', ignored [-Wunknown-warning-option]
  758 |   #pragma clang diagnostic ignored "-Wenum-constexpr-conversion"
      |                                    ^
reflect:770:22: error: no matching function for call to 'function_name'
  770 |   const auto names = detail::function_name<static_cast<E>(Ns+Min)...>();
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:36: note: in instantiation of function template specialization 'reflect::detail::(anonymous class)::operator()<0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL, 9UL, 10UL, 11UL, 12UL, 13UL, 14UL, 15UL, 16UL, 17UL, 18UL, 19UL, 20UL, 21UL, 22UL, 23UL, 24UL, 25UL, 26UL, 27UL, 28UL, 29UL, 30UL, 31UL, 32UL, 33UL, 34UL, 35UL, 36UL, 37UL, 38UL, 39UL, 40UL, 41UL, 42UL, 43UL, 44UL, 45UL, 46UL, 47UL, 48UL, 49UL, 50UL, 51UL, 52UL, 53UL, 54UL, 55UL, 56UL, 57UL, 58UL, 59UL, 60UL, 61UL, 62UL, 63UL, 64UL, 65UL, 66UL, 67UL, 68UL, 69UL, 70UL, 71UL, 72UL, 73UL, 74UL, 75UL, 76UL, 77UL, 78UL, 79UL, 80UL, 81UL, 82UL, 83UL, 84UL, 85UL, 86UL, 87UL, 88UL, 89UL, 90UL, 91UL, 92UL, 93UL, 94UL, 95UL, 96UL, 97UL, 98UL, 99UL, 100UL, 101UL, 102UL, 103UL, 104UL, 105UL, 106UL, 107UL, 108UL, 109UL, 110UL, 111UL, 112UL, 113UL, 114UL, 115UL, 116UL, 117UL, 118UL, 119UL, 120UL, 121UL, 122UL, 123UL, 124UL, 125UL, 126UL, 127UL, 128UL>' requested here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                                    ^
reflect:799:95: note: in instantiation of variable template specialization 'reflect::detail::enum_cases' requested here
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                               ^
reflect:1305:25: note: in instantiation of default argument for 'enumerators<reflect::test::e1, 0, 128>' required here
 1305 |     static_assert(1u == enumerators<reflect::test::e1>.size());
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:564:52: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Vs'
  564 | template<auto...  Vs> [[nodiscard]] constexpr auto function_name() noexcept -> std::string_view { return std::source_location::current().function_name(); }
      |                                                    ^
reflect:565:52: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Ts'
  565 | template<class... Ts> [[nodiscard]] constexpr auto function_name() noexcept -> std::string_view { return std::source_location::current().function_name(); }
      |                                                    ^
reflect:769:23: error: constexpr variable 'enum_cases<reflect::test::e1, 0, 128>' must be initialized by a constant expression
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  770 |   const auto names = detail::function_name<static_cast<E>(Ns+Min)...>();
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  771 |   const auto begin = detail::enum_name_info::begin;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  772 |   const auto end = std::size(names) - detail::enum_name_info::end;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  773 |   detail::static_vector<std::underlying_type_t<E>, sizeof...(Ns)> cases{};
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  774 |   std::underlying_type_t<E> index{};
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  775 |   auto valid = true;
      |   ~~~~~~~~~~~~~~~~~~
  776 |   for (auto i = begin; i < end; ++i) {
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  777 |     if (names[i] == '(' and names[i+1] != ')') {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  778 |       valid = false;
      |       ~~~~~~~~~~~~~~
  779 |     } else if (names[i] == ' ') {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  780 |       valid = true;
      |       ~~~~~~~~~~~~~
  781 |     } else if (names[i] == ',' or i == end-1) {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  782 |       if (valid) { cases.push_back(index+Min); }
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  783 |       ++index;
      |       ~~~~~~~~
  784 |       valid = true;
      |       ~~~~~~~~~~~~~
reflect:799:95: note: in instantiation of variable template specialization 'reflect::detail::enum_cases' requested here
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                               ^
reflect:1305:25: note: in instantiation of default argument for 'enumerators<reflect::test::e1, 0, 128>' required here
 1305 |     static_assert(1u == enumerators<reflect::test::e1>.size());
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1305:54: note: while checking a default template argument used here
 1305 |     static_assert(1u == enumerators<reflect::test::e1>.size());
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e1, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1306:54: note: while checking a default template argument used here
 1306 |     static_assert(0u == enumerators<reflect::test::e1>[0].first);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e1, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
reflect:770:22: error: no matching function for call to 'function_name'
  770 |   const auto names = detail::function_name<static_cast<E>(Ns+Min)...>();
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:36: note: in instantiation of function template specialization 'reflect::detail::(anonymous class)::operator()<0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL, 9UL, 10UL, 11UL, 12UL, 13UL, 14UL, 15UL, 16UL, 17UL, 18UL, 19UL, 20UL, 21UL, 22UL, 23UL, 24UL, 25UL, 26UL, 27UL, 28UL, 29UL, 30UL, 31UL, 32UL, 33UL, 34UL, 35UL, 36UL, 37UL, 38UL, 39UL, 40UL, 41UL, 42UL, 43UL, 44UL, 45UL, 46UL, 47UL, 48UL, 49UL, 50UL, 51UL, 52UL, 53UL, 54UL, 55UL, 56UL, 57UL, 58UL, 59UL, 60UL, 61UL, 62UL, 63UL, 64UL, 65UL, 66UL, 67UL, 68UL, 69UL, 70UL, 71UL, 72UL, 73UL, 74UL, 75UL, 76UL, 77UL, 78UL, 79UL, 80UL, 81UL, 82UL, 83UL, 84UL, 85UL, 86UL, 87UL, 88UL, 89UL, 90UL, 91UL, 92UL, 93UL, 94UL, 95UL, 96UL, 97UL, 98UL, 99UL, 100UL, 101UL, 102UL, 103UL, 104UL, 105UL, 106UL, 107UL, 108UL, 109UL, 110UL, 111UL, 112UL, 113UL, 114UL, 115UL, 116UL, 117UL, 118UL, 119UL, 120UL, 121UL, 122UL, 123UL, 124UL, 125UL, 126UL, 127UL, 128UL>' requested here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                                    ^
reflect:799:95: note: in instantiation of variable template specialization 'reflect::detail::enum_cases' requested here
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                               ^
reflect:1312:25: note: in instantiation of default argument for 'enumerators<reflect::test::e3, 0, 128>' required here
 1312 |     static_assert(3u == enumerators<reflect::test::e3>.size());
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:564:52: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Vs'
  564 | template<auto...  Vs> [[nodiscard]] constexpr auto function_name() noexcept -> std::string_view { return std::source_location::current().function_name(); }
      |                                                    ^
reflect:565:52: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'Ts'
  565 | template<class... Ts> [[nodiscard]] constexpr auto function_name() noexcept -> std::string_view { return std::source_location::current().function_name(); }
      |                                                    ^
reflect:769:23: error: constexpr variable 'enum_cases<reflect::test::e3, 0, 128>' must be initialized by a constant expression
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  770 |   const auto names = detail::function_name<static_cast<E>(Ns+Min)...>();
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  771 |   const auto begin = detail::enum_name_info::begin;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  772 |   const auto end = std::size(names) - detail::enum_name_info::end;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  773 |   detail::static_vector<std::underlying_type_t<E>, sizeof...(Ns)> cases{};
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  774 |   std::underlying_type_t<E> index{};
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  775 |   auto valid = true;
      |   ~~~~~~~~~~~~~~~~~~
  776 |   for (auto i = begin; i < end; ++i) {
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  777 |     if (names[i] == '(' and names[i+1] != ')') {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  778 |       valid = false;
      |       ~~~~~~~~~~~~~~
  779 |     } else if (names[i] == ' ') {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  780 |       valid = true;
      |       ~~~~~~~~~~~~~
  781 |     } else if (names[i] == ',' or i == end-1) {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  782 |       if (valid) { cases.push_back(index+Min); }
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  783 |       ++index;
      |       ~~~~~~~~
  784 |       valid = true;
      |       ~~~~~~~~~~~~~
reflect:799:95: note: in instantiation of variable template specialization 'reflect::detail::enum_cases' requested here
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                               ^
reflect:1312:25: note: in instantiation of default argument for 'enumerators<reflect::test::e3, 0, 128>' required here
 1312 |     static_assert(3u == enumerators<reflect::test::e3>.size());
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1312:54: note: while checking a default template argument used here
 1312 |     static_assert(3u == enumerators<reflect::test::e3>.size());
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e3, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1313:54: note: while checking a default template argument used here
 1313 |     static_assert(0u == enumerators<reflect::test::e3>[0].first);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e3, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1314:54: note: while checking a default template argument used here
 1314 |     static_assert(1u == enumerators<reflect::test::e3>[1].first);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e3, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
reflect:799:87: error: non-type template argument is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:1315:54: note: while checking a default template argument used here
 1315 |     static_assert(2u == enumerators<reflect::test::e3>[2].first);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
reflect:799:87: note: initializer of 'enum_cases<reflect::test::e3, 0, 128>' is not a constant expression
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^
reflect:799:87: note: in call to 'static_vector(enum_cases)'
  799 | template<class E, int Min = enum_min(E{}), int Max = enum_max(E{}), auto enum_cases = detail::enum_cases<E, Min, Max>>
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reflect:769:23: note: declared here
  769 | inline constexpr auto enum_cases = []<auto... Ns>(std::index_sequence<Ns...>) {
      |                       ^
2 warnings and 10 errors generated.
em++: error: '/home/gene/Coding/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/home/gene/Coding/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -x c++ -std=c++20 -O3 -DNDEBUG reflect -c -o /tmp/emscripten_temp_491npa99/reflect_0.o' failed (returned 1)
```

</details>

**Comment by krzysztof-jusiak** [comment]
Thanks @SGSSGene for reporting it. I also noted similar issues on the newest clang-trunk, so looking into it. BTW is there a way to verify emscripten on godbolt?

**Comment by SGSSGene** [comment]
It seems to be a very similar error to the current clang-trunk version.

I couldn't find a way to verify emscripten on godbolt. There exists a WebAssembly clang version, but without emscripten, which doesn't make it suitable for testing this.
